CREATE TABLE audit.application_reference (
  app_id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
  application_short_name STRING,
  source_category STRING,
  line_of_business STRING,
  insurance_type STRING,
  application_name STRING,
  application_description STRING,
  active_status STRING DEFAULT 'Y',
  validation_summary_option STRING DEFAULT '{}',
  reconcilation_summary_option STRING DEFAULT '{}',
  success_email STRING,
  failure_email STRING)
USING delta
TBLPROPERTIES (
  'delta.feature.allowColumnDefaults' = 'supported',
  'delta.feature.identityColumns' = 'supported',
  'delta.minReaderVersion' = '1',
  'delta.minWriterVersion' = '7')
